import { Ticket } from '../types';

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'chm-1001',
    codigo: '#CHM-1001',
    titulo: 'Vazamento de Óleo Hidráulico',
    equipamento: 'Prensa Hidráulica 120T',
    setor: 'Setor de Estamparia',
    prioridade: 'Alta',
    categoria: 'Hidráulica',
    descricao: 'Presença de vazamento contínuo de óleo no pistão principal. Pressão do sistema oscilando durante o ciclo de prensagem.',
    status: 'Em Andamento',
    operador_nome: 'João Operador',
    operador_id: 'operador-1',
    mecanico_nome: 'Carlos Mecânico',
    mecanico_id: 'mecanico-1',
    data_abertura: new Date(Date.now() - 3600000 * 5).toISOString(),
    data_inicio: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'chm-1002',
    codigo: '#CHM-1002',
    titulo: 'Ruído Anormal no Spindle',
    equipamento: 'Torno CNC Mazak 02',
    setor: 'Usinagem de Precisão',
    prioridade: 'Crítica',
    categoria: 'Mecânica',
    descricao: 'Barulho de atrito metálico e vibração excessiva no fuso principal quando atinge rotação acima de 2000 RPM. Equipamento parado para evitar danos maiores.',
    status: 'Aberto',
    operador_nome: 'João Operador',
    operador_id: 'operador-1',
    data_abertura: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'chm-1003',
    codigo: '#CHM-1003',
    titulo: 'Troca de Rolamento da Esteira',
    equipamento: 'Esteira Transportadora T-04',
    setor: 'Linha de Montagem A',
    prioridade: 'Média',
    categoria: 'Mecânica',
    descricao: 'Rolamento da polia motriz apresentando travamento esporádico. A esteira dá pequenos trancos.',
    status: 'Encerrado',
    operador_nome: 'João Operador',
    operador_id: 'operador-1',
    mecanico_nome: 'Carlos Mecânico',
    mecanico_id: 'mecanico-1',
    descricao_solucao: 'Substituído o rolamento estragado modelo 6205-2RS por um novo da marca SKF. Realizado alinhamento da polia e lubrificação da corrente motriz.',
    pecas_utilizadas: '1x Rolamento SKF 6205-2RS, 500ml Graxa Lítio MP2',
    tempo_manutencao: '1 hora e 45 minutos',
    causa_raiz: 'Desgaste natural por tempo de uso prolongado',
    data_abertura: new Date(Date.now() - 3600000 * 24).toISOString(),
    data_inicio: new Date(Date.now() - 3600000 * 20).toISOString(),
    data_encerramento: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 'chm-1004',
    codigo: '#CHM-1004',
    titulo: 'Sensor Pneumático Descalibrado',
    equipamento: 'Robô de Solda ABB #1',
    setor: 'Célula de Caldeiraria',
    prioridade: 'Baixa',
    categoria: 'Pneumática',
    descricao: 'Atuador pneumático da garra de fixação está demorando para recuar. Possível sujeira na válvula solenóide.',
    status: 'Aguardando Peça',
    operador_nome: 'João Operador',
    operador_id: 'operador-1',
    mecanico_nome: 'Carlos Mecânico',
    mecanico_id: 'mecanico-1',
    descricao_solucao: 'Diagnóstico realizado. Válvula direcional 5/2 vias está com diafragma interno rompido. Solicitado componente no almoxarifado.',
    pecas_utilizadas: 'Aguardando válvula Festo 5/2 NPT',
    tempo_manutencao: '30 minutos (diagnóstico)',
    causa_raiz: 'Falta de purga na linha de ar comprimido (umidade)',
    data_abertura: new Date(Date.now() - 3600000 * 12).toISOString(),
    data_inicio: new Date(Date.now() - 3600000 * 10).toISOString(),
  }
];
